date: 01-11-2013
slug: the-internet-is-a-universal-service
title: The Internet is a universal service
tags:
  - google
  - internet
  - estonia
images:
  twitter-card:
    src: 1f6f0.svg.png
  screen:
    src: screen.png
