date: 09-24-2011
slug: dynamically-coloring-a-favicon
title: Dynamically coloring a favicon
tags:
  - html
  - chrome
  - extensions
  - javascript
  - twitter
images:
  twitter-card:
    src: favicon1.png
  favicon1:
    src: favicon1.png
  favicon1smaller:
    src: favicon1.png
    metadata:
      style: "width:240px"
  favicon2:
    src: favicon2.png
  favicon2smaller:
    src: favicon2.png
    metadata:
      style: "width:240px"
  favicon3:
    src: favicon3.png
  twitterbars:
    src: twitterbars.png
  twitterbars2:
    src: twitterbars2.png
