date: 05-05-2016
slug: the-holy-mountain
title: The Holy Mountain (1973)
tags:
  - cinemaclub
  - reviews
images:
  twitter-card:
    src: holymountain-paint01-480-nosound.mp4.png
  insides:
    src: holymountain-insides-480-nosound.mp4.png
  paint01:
    src: holymountain-paint01-480-nosound.mp4.png
  paint02:
    src: holymountain-paint02-480-nosound.mp4.png
  ribbon:
    src: holymountain-ribbon-480-nosound.mp4.png
  sausages:
    src: holymountain-sausages-480-nosound.mp4.png
  smoke:
    src: holymountain-smoke-480-nosound.mp4.png
  strawberries:
    src: holymountain-strawberries-480-nosound.mp4.png
