application: roomanna-www-hrd
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico.png
  upload: static/favicon.ico.png

- url: /static/dev
  static_dir: static/dev/
  expiration: "1d"

- url: /static
  static_dir: static/
  expiration: "365d"

- url: /.*
  script: main.py
