runtime: go112
default_expiration: "7d"
main: github.com/kurrik/roomanna/www.roomanna.com/src/server

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico.png
  upload: static/favicon.ico.png

- url: /static/dev
  static_dir: static/dev/
  expiration: "1s"

- url: /static
  static_dir: static/
  expiration: "365d"

- url: /.*
  script: auto
  secure: always
