date: 09-14-2017
slug: the-exterminating-angel
title: The Exterminating Angel (1962)
tags:
  - cinemaclub
  - reviews
images:
  twitter-card:
    src: "exterminating-angel.jpg"
  exterminating-angel:
    src: "exterminating-angel.jpg"
    metadata:
      alt: "Still from The Exterminating Angel"
