date: 01-06-2011
slug: add-on-con
title: Add-on-Con 2010
tags:
  - chrome
  - extensions
  - presentations
  - work
images:
  twitter-card:
    src: "melting.png"
  melting:
    src: "melting.png"
    metadata:
      alt: Melting effect from DOOM
