date: 05-08-2016
slug: throne-of-blood
title: Throne of Blood (1957)
tags:
  - cinemaclub
  - reviews
images:
  twitter-card:
    src: throne-of-blood-mifune.png
  arrows:
    src: throne-of-blood-arrows-480.mp4.png
  aspect:
    src: throne-of-blood-aspect.png
    metadata:
      alt: A crowded 1.37:1 shot
  death:
    src: throne-of-blood-death-480.mp4.png
  mifune:
    src: throne-of-blood-mifune.png
    metadata:
      alt: Mifune staring at the camera
