date: 09-21-2011
slug: my-first-weeks-at-twitter
title: My First Weeks at Twitter...
tags:
  - arne
  - twitter
  - work
images:
  twitter-card:
    src: "bird-shark.jpg"
  twitter:
    src: "twitter.png"
