runtime: go112
default_expiration: "7d"
main: github.com/kurrik/roomanna/www.roomanna.com/src/server

handlers:
- url: /favicon.ico
  static_files: www.roomanna.com/src/server/static/favicon.ico.png
  upload: www.roomanna.com/src/server/static/static/favicon.ico.png

- url: /static
  static_dir: www.roomanna.com/src/server/static/
  expiration: "365d"

- url: /.*
  script: auto
  secure: always
