application: roomanna-www-hrd
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico.png
  upload: img/favicon.ico.png

- url: /css/fonts
  static_dir: css/fonts/
  expiration: "1d"
  mime_type: "application/octet-stream"

- url: /css
  static_dir: css/
  expiration: "1d"

- url: /img
  static_dir: img/
  expiration: "1d"

- url: /js
  static_dir: js/
  expiration: "1d"

- url: /.*
  script: main.py
