runtime: go112
default_expiration: "7d"
main: github.com/kurrik/roomanna/blog.roomanna.com/src/server

handlers:
- url: /(.*\.(gif|png|jpg|mp4|js|css|woff|ico))$
  static_files: build/content/\1
  upload: build/content/.*\.(gif|png|jpg|mp4|js|css|woff|ico)$
  expiration: "365d"

- url: /.*
  script: auto
  secure: always
