date: 05-20-2011
slug: simple-go-server
title: Simple Go Server
tags:
  - go
  - appengine
images:
  twitter-card:
    src: "gogopher.png"
  gogopher-right:
    src: "gogopher.png"
    metadata:
      alt: Go Gopher
      class: pull-right
